{% set version = "1.4.1" %}

package:
  name: pocean-core
  version: {{ version }}

source:
  url: https://github.com/pyoceans/pocean-core/archive/{{ version }}.tar.gz
  sha256: e2afa3aef49c143606377ca2059ecb16f4b199c0c2a8fc473ae8fba07c63ed9e

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - netcdf4
    - numpy >=1.14
    - pandas >=0.21.0
    - pygc >=1.2.0
    - python-dateutil
    - pytz
    - shapely
    - simplejson
    - six

test:
  source_files:
    - pocean
  requires:
    - pytest
  imports:
    - pocean
    - pocean.dsg
    - pocean.grid
  commands:
    - py.test -s -rxs -v pocean

about:
  home: https://github.com/axiom-data-science/pocean-core
  license: MIT
  license_file: LICENSE.txt
  summary: 'A python framework for working with met-ocean data.'

extra:
  recipe-maintainers:
    - daf
    - kwilcox
    - ocefpaf
