{% set version = "1.3.0" %}

package:
  name: pocean-core
  version: {{ version }}

source:
  url: https://github.com/pyoceans/pocean-core/archive/{{ version }}.tar.gz
  sha256: 6d0ed17fddbd02a3abc7b88118c4b240ec05a8009cdf74ab74ac7a5a0ae5c546

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - netcdf4
    - numpy
    - pandas >=0.21.0
    - pygc >=1.2.0
    - python-dateutil
    - pytz
    - shapely
    - simplejson
    - six

test:
  source_files:
    - pocean
  requires:
    - pytest
  imports:
    - pocean
    - pocean.dsg
    - pocean.grid
    - pocean.tests
  commands:
    - py.test -s -rxs -v pocean

about:
  home: https://github.com/axiom-data-science/pocean-core
  license: MIT
  license_file: LICENSE.txt
  summary: 'A python framework for working with met-ocean data.'

extra:
  recipe-maintainers:
    - daf
    - kwilcox
    - ocefpaf
