{% set version = "3.0.0" %}

package:
  name: pocean-core
  version: {{ version }}

source:
  url: https://github.com/pyoceans/pocean-core/archive/{{ version }}.tar.gz
  sha256: 614d212eee36f8dad43cddfd339d6794c30cce305700d76c9cc47bef1af1919f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<4.0
    - pip
  run:
    - python >=3.6,<4.0
    - netcdf4
    - numpy >=1.15
    - pandas >=1.0.5
    - python-dateutil
    - pytz
    - shapely
    - simplejson
    - cftime >=1.2.1

test:
  source_files:
    - pocean
  requires:
    - pytest
    - pip
  imports:
    - pocean
    - pocean.dsg
    - pocean.grid
  commands:
    - pip check
    - pytest -s -rxs -v pocean

about:
  home: https://github.com/axiom-data-science/pocean-core
  license: MIT
  license_file: LICENSE.txt
  summary: A python framework for working with met-ocean data.

extra:
  recipe-maintainers:
    - daf
    - kwilcox
    - ocefpaf
