{% set name = "pocean-core" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: efa98f35689cc4de0f4800e7dadbe34aef7d6b89e66f0ecd5a6fa6d82f74ce65

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - setuptools >=42
    - setuptools-scm >=3.4
    - wheel
    - pip
  run:
    - python >=3.7,<4.0
    - cftime >=1.2.1
    - netcdf4
    - numpy >=1.20
    - pandas >=1.0.5
    - python-dateutil
    - pytz
    - shapely >=1.8
    - simplejson

test:
  source_files:
    - pocean
  requires:
    - pip
  imports:
    - pocean
    - pocean.dsg
    - pocean.grid
  commands:
    - pip check

about:
  home: https://github.com/axiom-data-science/pocean-core
  license: MIT
  license_file: LICENSE.txt
  summary: A python framework for working with met-ocean data.

extra:
  recipe-maintainers:
    - daf
    - kwilcox
    - ocefpaf
