{% set version = "1.1.0" %}

package:
  name: pocean-core
  version: {{ version }}

source:
  fn: pocean-core-{{ version }}.tar.gz
  url: https://github.com/pyoceans/pocean-core/archive/{{ version }}.tar.gz
  sha256: f9e012afd8a12d553f0f64d7badb020ce21bd964e6861ee81d67f7db1f18cc0f

build:
  number: 0
  skip: True  # [py2k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - netcdf4
    - numpy
    - pandas
    - pygc >=1.2.0
    - python-dateutil
    - pytz
    - shapely
    - simplejson
    - six

test:
  source_files:
    - pocean
  requires:
    - pytest
  imports:
    - pocean
    - pocean.dsg
    - pocean.grid
    - pocean.tests
  commands:
    - py.test -s -rxs -v pocean

about:
  home: https://github.com/axiom-data-science/pocean-core
  license: MIT
  license_file: LICENSE.txt
  summary: 'A python framework for working with met-ocean data.'

extra:
  recipe-maintainers:
    - daf
    - kwilcox
    - ocefpaf
