{% set version = "3.1.0" %}

package:
  name: pocean-core
  version: {{ version }}

source:
  url: https://github.com/pyoceans/pocean-core/archive/{{ version }}.tar.gz
  sha256: 6cbe18cc8002bec38da4c33cdebaf9bd7730b8528aece1110e0aa8b15a9ab5d0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<4.0
    - setuptools >=42
    - setuptools-scm >=3.4
    - wheel
    - pip
  run:
    - python >=3.7,<4.0
    - cftime >=1.2.1
    - netcdf4
    - numpy >=1.20
    - pandas >=1.0.5
    - python-dateutil
    - pytz
    - shapely >=1.8
    - simplejson

test:
  source_files:
    - pocean
  requires:
    - pytest
    - pip
  imports:
    - pocean
    - pocean.dsg
    - pocean.grid
  commands:
    - pip check
    - pytest -s -rxs -v pocean

about:
  home: https://github.com/axiom-data-science/pocean-core
  license: MIT
  license_file: LICENSE.txt
  summary: A python framework for working with met-ocean data.

extra:
  recipe-maintainers:
    - daf
    - kwilcox
    - ocefpaf
