travis:
  secure:
    BINSTAR_TOKEN: aBq3g1p5o86MmFtrvxaHdCuucIxlttBM8uEEv0HpVCN3REeL3cQo851uzBNDxYUfSG1Ihh1jMn21GamHCtMHGUqe8mIkjIHUUFqBFnDl9pNgTqC5kkXVbHkUfLwK6WI7OFkuzlTmOjiNZG19hl+9rRB/MY7dYatFVSV5GyO4mQpQjlU0gn+1uFo+L/hv2nGb8wfdcxYbQvydfjGfdtddWPpkaswOM6TV4pGX83pMHjmwK5WR4mt/ZQkZTFJTtK6gK4fO+rsva4hPcBuEQWJKGGU/GoTgHi4S2WEwn3kTDO0y5H+JOU+s+hzyf4xPmXeEsmopk+70uwtSQmRJCSKDL0NzQU7JllrbYOl4vnwPcF11Bfl1Bbpq+1U/R3fLoxmVirfWt+RGbBl+0jGWDfE1mEIbevgEZSV30NbSdVqACfxmWzIVDjGMSoIaOi+BmJ4c2lHwKrno07xw+PAsWItiJVDi/bFIO58QGE+MQSxAC3BastBVGNwYled1Z9u6uuzAPx3k1FmD0e1uJPyCU0u1IJ8gbohXPLhL3aGck+INt6IZVasbFrcsPubhC30mna2F6z6QBzc170dvgceCuyD+hNM6tjLKBENkHSX9OaR87rcnxdRyDd1a16kyn82iTH2xwbHyrgWOzWCvMNaYY2jEWmQF0+NWXXERnj7CU3oSyro=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
