travis:
  secure:
    BINSTAR_TOKEN: ZYBA9m5hCHgqRGzsOvmK5MH38miYAM8seA12eueUqjHe/mcFdXlS4kYURFxrU+lh6z/Wyl/ncWGQu8kFiunl1lv0xRU97CE1ReDJW1RQwI18eCrTmctTn3kj3SeA5wb6vccpb5gK6Z13eD5rsEAdZ6XoKImbacBotcw4WLs+VMJW3Wp/0rIPyB7xc9t3qPFab1I9WwZBiwcWDu+17+tYtwJGmUMgKpjJhpUsMo0UdvATRdsQzt9X57CwSRYQJpDTU/nl64vwayxN+dYOXywXmsG+LxpIFj+K311hyxh1LXUztjRdC+uJwyQrgK1fJdIUaAMofxA/mOHYt9YiaItWmMn4+p/q0ed304e7qfvfUWv300sTHvWalIAQJQRyQx6jpC+6lq9lvV4lNkbWhHaXKKKODR4FkPpZeNPgrDsd0AbMmO4wsM1RoWJMOM6HRFDtEMKjq9rcvBcO6/f+s9dbVIiJcxkwazDGUKtrVgVlXIVJmZt5awYPV/W84ChNbNkWlcCdf715QOld7opMG7igaW+rkXnEFNMQvWzI9SqwsVs3rvP+luJMFlTBSvi+3Dt7uw/WOiU3YVpXK0EUWd1a238/W2WPQL4Hbn4YAY9XmfDRJG9LCtmcpB4IGVp6b1B86IPf5T4Ve+QXWhQq40w21yLM8Q3m/+RqXxOs4WnxyZY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
